"""empty message

Revision ID: 183b423676af
Revises: 771b65fafa0c
Create Date: 2023-11-27 00:44:30.595294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183b423676af'
down_revision = '771b65fafa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criacao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('criacao')

    # ### end Alembic commands ###
