"""empty message

Revision ID: 28acf6e7847a
Revises: c12964e7638c
Create Date: 2023-12-12 21:56:39.155345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28acf6e7847a'
down_revision = 'c12964e7638c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_dividends', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.drop_column('total_dividends')

    # ### end Alembic commands ###
