"""empty message

Revision ID: 2ed533444988
Revises: 72aeba7ef947
Create Date: 2023-12-02 16:11:34.669397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed533444988'
down_revision = '72aeba7ef947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_conta')
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.String(), nullable=True))
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('saldo')

    op.create_table('_alembic_tmp_conta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('criacao', sa.DATE(), nullable=True),
    sa.Column('saldo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
