"""empty message

Revision ID: 34cdc676224b
Revises: 7a1d4723ac28
Create Date: 2023-12-04 14:12:07.672097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cdc676224b'
down_revision = '7a1d4723ac28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_acoes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_criptos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_criptosR', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('total_criptosR')
        batch_op.drop_column('total_criptos')
        batch_op.drop_column('total_acoes')
        batch_op.drop_column('total')

    # ### end Alembic commands ###
