"""empty message

Revision ID: 39dd9a683ae0
Revises: 27fbfe9b123d
Create Date: 2023-11-26 23:58:31.779868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dd9a683ae0'
down_revision = '27fbfe9b123d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_carteira_acoes')
    with op.batch_alter_table('carteira_acoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_udpate', sa.Date(), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_acoes', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('last_udpate')

    op.create_table('_alembic_tmp_carteira_acoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('valor_pago_total', sa.FLOAT(), nullable=True),
    sa.Column('rentabilidade_total', sa.FLOAT(), nullable=True),
    sa.Column('total_dividendos', sa.FLOAT(), nullable=True),
    sa.Column('valor_atual_total', sa.FLOAT(), nullable=True),
    sa.Column('lucro_prejuizo', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
