"""empty message

Revision ID: 47de003101f5
Revises: 91be3a83f828
Create Date: 2023-10-31 12:01:37.669968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47de003101f5'
down_revision = '91be3a83f828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_cripto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_pago_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_atual_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rentabilidade_total', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_cripto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rentabilidade_total')
        batch_op.drop_column('valor_atual_total')
        batch_op.drop_column('valor_pago_total')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
