"""empty message

Revision ID: 4a0b350aa6ad
Revises: 28acf6e7847a
Create Date: 2023-12-14 15:21:58.487601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0b350aa6ad'
down_revision = '28acf6e7847a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yield_total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.drop_column('yield_total')

    # ### end Alembic commands ###
