"""empty message

Revision ID: 771b65fafa0c
Revises: 663e65ddb3ac
Create Date: 2023-11-27 00:28:20.281322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771b65fafa0c'
down_revision = '663e65ddb3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_cripto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_cripto', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
