"""empty message

Revision ID: 7a1d4723ac28
Revises: bb0538306398
Create Date: 2023-12-03 18:32:05.950749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1d4723ac28'
down_revision = 'bb0538306398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
