"""empty message

Revision ID: 91be3a83f828
Revises: 
Create Date: 2023-10-20 22:59:36.328722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91be3a83f828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), nullable=True),
    sa.Column('preco_pago', sa.FLOAT(), nullable=True),
    sa.Column('valor_pago', sa.FLOAT(), nullable=True),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('data_compra', sa.DATE(), nullable=True),
    sa.Column('preco_atual', sa.FLOAT(), nullable=True),
    sa.Column('valor_atual', sa.FLOAT(), nullable=True),
    sa.Column('lucro_prejuizo', sa.FLOAT(), nullable=True),
    sa.Column('rentabilidade', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
