"""empty message

Revision ID: bb0538306398
Revises: a19169adb425
Create Date: 2023-12-03 18:04:24.384120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0538306398'
down_revision = 'a19169adb425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
