"""empty message

Revision ID: c12964e7638c
Revises: 34cdc676224b
Create Date: 2023-12-12 13:23:29.869129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12964e7638c'
down_revision = '34cdc676224b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_yield', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.drop_column('last_yield')

    # ### end Alembic commands ###
